// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Lzxd6iCIh6YKckN5OVy-EcZpTu02wZM',
    appId: '1:960818074798:android:481363ed6667261059c93f',
    messagingSenderId: '960818074798',
    projectId: 'hunger-help-vitb',
    storageBucket: 'hunger-help-vitb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYWJrFnW7D9MRWg5SCMu5SB68XRW_cBjk',
    appId: '1:960818074798:ios:0c1e3a834e565a3359c93f',
    messagingSenderId: '960818074798',
    projectId: 'hunger-help-vitb',
    storageBucket: 'hunger-help-vitb.appspot.com',
    androidClientId: '960818074798-7lafo7fjf9vglgtqhdrk6hdkfra1pkl0.apps.googleusercontent.com',
    iosClientId: '960818074798-v9l66u78emfg6c6vpqi608flqkt40nk7.apps.googleusercontent.com',
    iosBundleId: 'com.example.hungerHelp',
  );
}
